name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # Optional: customize the release type
          # release-type: simple

          # Optional: customize the token (defaults to GITHUB_TOKEN)
          # token: ${{ secrets.GITHUB_TOKEN }}
